NPD=--no-print-directory

release: FORCE
	make $(NPD) -C ../ release

run_release: FORCE
	make $(NPD) -C ../ run_release

debug: FORCE
	make $(NPD) -C ../ debug

run_debug: FORCE
	make $(NPD) -C ../ run_debug

clean: FORCE
	make $(NPD) -C ../ clean

FORCE:


